apiVersion: apps/v1
kind: Deployment
metadata:
  name: BiddingManagement
  labels:
    app: BiddingManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BiddingManagement
  template:
    metadata:
      labels:
        app: BiddingManagement
    spec:
      containers:
        - name: BiddingManagement
          image: username/BiddingManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5